version: '3.7'

services:
  # Backend service
  backend:
    build: ./server
    container_name: phone-lookup-backend
    restart: always
    env_file:
      - .env
    expose:
      - "5000" # Chỉ expose cổng cho nội bộ, không cần public
    networks:
      - app-network

  # Frontend service (Nginx)
  frontend:
    image: nginx:latest
    container_name: phone-lookup-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443" # Thêm cổng 443 cho HTTPS
    volumes:
      - /home/tt/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Map file nginx.conf
      - /home/tt/ssl/cloudflare-cert.pem:/etc/nginx/ssl/cloudflare-cert.pem # Map chứng chỉ SSL
      - /home/tt/ssl/cloudflare-key.pem:/etc/nginx/ssl/cloudflare-key.pem # Map key SSL
      - ./client/build:/usr/share/nginx/html # Giả sử thư mục build của frontend nằm ở ./client/build
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
