version: '3.7'

services:
  # Backend service
  backend:
    build: ./server
    container_name: phone-lookup-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./client
    container_name: phone-lookup-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
