version: '3.8'

services:
  # Backend service
  backend:
    build: ./server
    container_name: phone-lookup-backend
    restart: always
    volumes:
      - ./server/phone_lookup.db:/app/phone_lookup.db
    ports:
      - "5000:5000"
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./client
    container_name: phone-lookup-frontend
    restart: always
    volumes:
      - ./client/build:/app/build
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
