name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push client Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
        
    - name: Build and push server Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        envs: DB_USER,DB_PASSWORD,DB_SERVER,DB_NAME  # Truyền biến vào script
        script: |
          cd ~/deploy
          
          # Pull newest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
          
          # Stop and remove existing containers
          docker-compose down

          # Tạo file .env với double quote để thay thế biến
          cat > .env << EOF
          
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_SERVER=${DB_SERVER}
          DB_NAME=${DB_NAME}
          NODE_ENV=production
          PORT=5000
          EOF

          # Tạo docker-compose.yml (giữ single quote vì có biến GitHub Secrets)
          cat > docker-compose.yml << 'EOF'
          version: '3.8'
          
          services:
            client:
              image: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
              container_name: phone-lookup-frontend
              restart: always
              ports:
                - "80:80"
              depends_on:
                - server
              networks:
                - app-network
            
            server:
              image: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
              container_name: phone-lookup-backend
              restart: always
              env_file:
                - .env
              networks:
                - app-network

          networks:
            app-network:
              driver: bridge
          EOF
          
          # Start new containers
          docker-compose up -d