name: Deploy to VPS

on:
  push:
    branches: [ main ]  # Thay đổi thành branch chính của bạn nếu cần (ví dụ: master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push client Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
        
    - name: Build and push server Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /path/to/deployment
          
          # Pull newest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
          
          # Stop and remove existing containers
          docker-compose down
          
          # Create docker-compose file if it doesn't exist
          cat > docker-compose.yml << 'EOL'
          version: '3'
          
          services:
            client:
              image: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-client:latest
              restart: always
              ports:
                - "80:80"
            
            server:
              image: ${{ secrets.DOCKER_USERNAME }}/phone-lookup-server:latest
              restart: always
              volumes:
                - ./data:/app/data
          EOL
          
          # Start new containers
          docker-compose up -d
